# Generated by Django 6.0.6 on 2026-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetyreport',
            name='area',
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='city',
            field=models.CharField(choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Nanded', 'Nanded'), ('Aurangabad', 'Aurangabad'), ('Other', 'Other')], default='Pune', max_length=50),
        ),
        migrations.AddField(
            model_name='safetyreport',
            name='locality',
            field=models.CharField(default='', help_text='e.g. Wagholi, Kharadi, Hinjewadi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safetyreport',
            name='category',
            field=models.CharField(choices=[('Street Lighting', 'Street Lighting'), ('Public Transport', 'Public Transport'), ('Late Night Safety', 'Late Night Safety'), ('Harassment Incident', 'Harassment Incident'), ('Crowded/Safe', 'Crowded/Safe')], max_length=50),
        ),
    ]
